{{- if .Values.project.create }}
{{- $projNamespace := (default "argocd" .Values.project.namespace) -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default .Values.name .Values.project.name }}
  namespace: {{ $projNamespace }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Parent project to deploy a number of my charts in a project by default

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
    #- namespace: '{{ .Values.namespace }}'
    #  name: '*'
    #  server: '*'
    #- namespace: '{{ .Values.namespace }}-*'
    #  name: '*'
    #  server: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*' # TODO Consider reducing scope
    kind: '*' 
#  - group: ''
#    kind: Namespace

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
#  namespaceResourceWhitelist: []
#  - group: 'apps'
#    kind: Deployment
#  - group: 'apps'
#    kind: StatefulSet
#  - group: 'apps'
#    kind: Application

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  roles:
  - name: read-only
    description: Read-only privileges to {{ default .Values.name .Values.project.name }}
    policies:
    - p, proj:{{ default .Values.name .Values.project.name }}:read-only, applications, get, {{ default .Values.name .Values.project.name }}/*, allow
    - p, proj:{{ default .Values.name .Values.project.name }}:read-only, applications, get, {{ $projNamespace }}/*, allow

  # TODO Sync windows restrict when Applications may be synced. https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/
  syncWindows: []

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  permitOnlyProjectScopedClusters: false

  # When using Applications-in-any-namespace, this field determines which namespaces this AppProject permits
  # Applications to reside in. Details: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
  #sourceNamespaces:
  #  - "{{ .Values.namespace }}"
  #  - "{{ .Values.namespace }}-*"
{{- end }}
